/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: VADC EMUX
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2023, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"
#include <stdio.h>

/*******************************************************************************
* Defines
*******************************************************************************/

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT              (1)

/* Define macro to set the loop count before printing debug messages */
#if ENABLE_XMC_DEBUG_PRINT
#define DEBUG_LOOP_COUNT_MAX                (1U)
#endif

#if (UC_SERIES == XMC14)
#define ADC_CONVERSION_EVENT_HANDLER        IRQ_Hdlr_19
#define INTERRUPT_PRIORITY_NODE_ID          IRQ19_IRQn
#else
#define ADC_CONVERSION_EVENT_HANDLER        VADC0_G0_0_IRQHandler
#define INTERRUPT_PRIORITY_NODE_ID          VADC0_G0_0_IRQn
#endif

/* Group 0 channel 1 pin is measured and converted */
#define CHANNEL_NUMBER    (1U)
#define VADC_GROUP_PTR    (VADC_G0)

/* Register result */
#define RES_REG_NUMBER    (0)

/* ADC Conversion rate (ms) */
#define TICK_PERIOD (10U)

/*******************************************************************************
* Function Name: ADC_CONVERSION_EVENT_HANDLER
********************************************************************************
* Summary:
* This is the interrupt handler function for the ADC end of conversion.
* The ADC result is retrieved after conversion inside this function.
* On board LED glows high when ADC counts are more than ADC_MID_OF_RANGE value.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/
void ADC_CONVERSION_EVENT_HANDLER(void)
{
    XMC_VADC_RESULT_SIZE_t result;

    /* Read the result register */
    result = XMC_VADC_GROUP_GetResult(VADC_GROUP_PTR, RES_REG_NUMBER);

    /* Acknowledge the interrupt */
    XMC_VADC_GROUP_QueueClearReqSrcEvent(VADC_GROUP_PTR);
    
    #if ENABLE_XMC_DEBUG_PRINT
    printf("%u\r\n",result);
    #endif
}

/*******************************************************************************
* Function Name: SysTick_Handler
********************************************************************************
* Summary:
* This is the interrupt handler function for the SysTick timer interrupt.
* It counts the time elapsed in milliseconds since the timer started.
*
* Parameters:
*  void
*
* Return:
*  void
*
*******************************************************************************/

void SysTick_Handler(void)
{
    /* Trigger next conversion */
    XMC_VADC_GROUP_QueueTriggerConversion(VADC_GROUP_PTR);
}

/*******************************************************************************
 * Function Name: main
 ********************************************************************************
 * Summary:
 * This is the main function. It initializes the SPI interface and configures
 * SPI block for transmitting data.
 *
 * Parameters:
 *  void
 *
 * Return:
 *  int
 *
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    #if ENABLE_XMC_DEBUG_PRINT
    /* Initialize retarget-io to use the debug UART port */
    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    printf("Initialization done\r\n");
    #endif

    NVIC_EnableIRQ(INTERRUPT_PRIORITY_NODE_ID);

    /* System timer configuration */
    SysTick_Config(SystemCoreClock / TICK_PERIOD);

    for (;;)
    {

    }
}

/* [] END OF FILE */
